version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
    ports:
    - 3306:3306
    expose:
      - 3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mymongo
    ports:
    - 27017:27017
    expose:
      - 27017
  
  app:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile.app
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_PORT=3306
      - MYSQL_PASSWORD=password
      - NODE_ENV=docker
    stdin_open: true
    tty: true
    expose:
      - 3000
    ports:
      - 3000:3000
  
  worker:
    depends_on:
      app:
        condition: service_started
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_PORT=3306
      - MYSQL_PASSWORD=password
      - NODE_ENV=docker
    stdin_open: true
    tty: true

volumes: 
  db: